default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: fmbot_development

test:
  <<: *default
  database: fmbot_test

production:
  <<: *default
  database: fmbot_production

staging:
  <<: *default
  database: fmbot_staging

